AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  TagEC2Resource:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::241348417343:role/LambdaAllowTaggingEC2Role'
      Events:
        CloudWatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - AWS API Call via CloudTrail
              source:
                - aws.ec2
              detail:
                eventSource:
                  - ec2.amazonaws.com
                eventName:
                  - CreateImage
                  - CreateSnapshot
                  - CreateVolume
                  - RunInstances
