AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  EnableVPCFlowLogs:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: s3://perkins-lambda-functions/EnableVPCFlowLogs-3b3ac446-dddd-4b2d-8674-d2a11f429597
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::241348417343:role/VPCEnableFlowLogsRoles'
      Events:
        CloudWatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - AWS API Call via CloudTrail
              source:
                - aws.ec2
              detail:
                eventSource:
                  - ec2.amazonaws.com
                eventName:
                  - CreateVpc
      Environment:
        Variables:
          ROLE_ARN: 'arn:aws:iam::241348417343:role/VPCEnableFlowLogsRoles'
